f=[0 pi/6 pi/6 pi];
H=[1 1 0 0];
M=31;
w=0:pi/30:pi;
h=hanning(M);
subplot(2,2,1);plot(w/pi,h);
title('Hanning Window (M=31)');
[H1 w]=freqz(h,1,1024);
subplot(2,2,2);plot(w/pi,abs(H1));
title('Frequency Response for Hanning Window Function');
B=fir1(M-1,1/6); 
[H2 w]=freqz(B,1,1024);
subplot(2, 2, 3);plot(w/pi,abs(H2));
ylabel('Amplitude');
xlabel('Radian Frequency');
title('Frequency Response of FIR filter using Hanning window');
gk=20.*log(abs(H2));
subplot(2,2,4);plot(w/pi,gk);
ylabel('dB');
xlabel('Radian Frequency');
